Repository enzo-project/enzo-e, pull requests merged in 2024-02, with the labels that each got.

#359 Bug fix for 2D gravity
  src/Enzo/gravity/solvers/EnzoSolverJacobi.cpp
  src/Enzo/gravity/solvers/EnzoSolverMg0.cpp
Labels: bug

#333 Convert Miscellaneous Enzo subdirectories into subcomponents (Build Restructuring Part 2)
  doc/source/devel/coding-guidelines.rst
  src/Enzo/CMakeLists.txt
  src/Enzo/_enzo.hpp
  src/Enzo/assorted/CMakeLists.txt
  src/Enzo/assorted/EnzoMethodHeat.cpp
  src/Enzo/assorted/EnzoMethodM1Closure.cpp
  src/Enzo/assorted/EnzoMethodTurbulence.cpp
  src/Enzo/assorted/assorted.hpp
  src/Enzo/charm_enzo.cpp
  src/Enzo/enzo-core/EnzoProblem.cpp
  src/Enzo/enzo-core/test_EnzoUnits.cpp
  src/Enzo/enzo-e.cpp
  src/Enzo/enzo_fortran.hpp
  src/Enzo/hydro-mhd/EnzoSourceInternalEnergy.cpp
  src/Enzo/initial/CMakeLists.txt
  src/Enzo/initial/EnzoInitialBCenter.cpp
  src/Enzo/initial/EnzoInitialBurkertBodenheimer.cpp
  src/Enzo/initial/EnzoInitialCloud.cpp
  src/Enzo/initial/EnzoInitialCollapse.cpp
  src/Enzo/initial/EnzoInitialCosmology.cpp
  src/Enzo/initial/EnzoInitialImplosion2.cpp
  src/Enzo/initial/EnzoInitialInclinedWave.cpp
  src/Enzo/initial/EnzoInitialInclinedWave.hpp
  src/Enzo/initial/EnzoInitialIsolatedGalaxy.cpp
  src/Enzo/initial/EnzoInitialSedovArray2.cpp
  src/Enzo/initial/EnzoInitialSedovArray3.cpp
  src/Enzo/initial/EnzoInitialSedovRandom.cpp
  src/Enzo/initial/EnzoInitialShockTube.cpp
  src/Enzo/initial/EnzoInitialShuCollapse.cpp
  src/Enzo/initial/EnzoInitialSoup.cpp
  src/Enzo/initial/EnzoInitialTurbulence.cpp
  src/Enzo/initial/initial.hpp
  src/Enzo/mesh/CMakeLists.txt
  src/Enzo/mesh/EnzoProlong.cpp
  src/Enzo/mesh/EnzoProlongMC1.cpp
  src/Enzo/mesh/EnzoProlongPoisson.cpp
  src/Enzo/mesh/EnzoRefineMass.cpp
  src/Enzo/mesh/EnzoRefineParticleMass.cpp
  src/Enzo/mesh/EnzoRefineShock.cpp
  src/Enzo/mesh/EnzoRestrict.cpp
  src/Enzo/mesh/mesh.hpp
  src/Enzo/tests/CMakeLists.txt
  src/Enzo/tests/EnzoInitialAccretionTest.cpp
  src/Enzo/tests/EnzoInitialBBTest.cpp
  src/Enzo/tests/EnzoInitialFeedbackTest.cpp
  src/Enzo/tests/EnzoInitialGrackleTest.cpp
  src/Enzo/tests/EnzoInitialMergeSinksTest.cpp
  src/Enzo/tests/EnzoInitialPpmlTest.cpp
  src/Enzo/tests/tests.hpp
  src/Enzo/utils/CMakeLists.txt
  src/Enzo/utils/EnzoCenteredFieldRegistry.cpp
  src/Enzo/utils/EnzoComputeCicInterp.cpp
  src/Enzo/utils/EnzoEFltArrayMap.cpp
  src/Enzo/utils/EnzoFieldAdaptor.cpp
  src/Enzo/utils/utils.hpp
Labels: build-system

#334 Convert `Enzo/gravity` into a distinct subcomponent (Build Restructuring Part 3)
  src/Enzo/CMakeLists.txt
  src/Enzo/_enzo.hpp
  src/Enzo/charm_enzo.cpp
  src/Enzo/enzo-core/EnzoProblem.cpp
  src/Enzo/gravity/CMakeLists.txt
  src/Enzo/gravity/EnzoComputeAcceleration.cpp
  src/Enzo/gravity/EnzoMethodBackgroundAcceleration.cpp
  src/Enzo/gravity/EnzoMethodGravity.cpp
  src/Enzo/gravity/EnzoMethodPmDeposit.cpp
  src/Enzo/gravity/gravity.hpp
  src/Enzo/gravity/matrix/EnzoMatrixDiagonal.cpp
  src/Enzo/gravity/matrix/EnzoMatrixIdentity.cpp
  src/Enzo/gravity/matrix/EnzoMatrixLaplace.cpp
  src/Enzo/gravity/solvers/EnzoSolverBiCgStab.cpp
  src/Enzo/gravity/solvers/EnzoSolverCg.cpp
  src/Enzo/gravity/solvers/EnzoSolverDd.cpp
  src/Enzo/gravity/solvers/EnzoSolverDiagonal.cpp
  src/Enzo/gravity/solvers/EnzoSolverJacobi.cpp
  src/Enzo/gravity/solvers/EnzoSolverMg0.cpp
Labels: build-system

#278 Introduce some debugging functions to dump arrays to disk
  doc/source/devel/debugging.rst
  doc/source/devel/index.rst
  src/Cello/CMakeLists.txt
  src/Cello/_disk.hpp
  src/Cello/cello.hpp
  src/Cello/data_Field.hpp
  src/Cello/data_FieldData.cpp
  src/Cello/data_FieldDescr.hpp
  src/Cello/disk_utils.hpp
  src/Cello/test_DiskUtils.cpp
  src/Cello/test_Type.cpp
  src/Cello/test_ViewCollec.cpp
  src/Cello/test_ViewTestTools.hpp
  test/CMakeLists.txt
Labels: enhancement

#332 Convert `Enzo/hydro-mhd` into a subcomponent (Build Restructuring Part 1)
  src/Enzo/CMakeLists.txt
  src/Enzo/_enzo.hpp
  src/Enzo/charm_enzo.cpp
  src/Enzo/enzo-core/EnzoProblem.cpp
  src/Enzo/enzo_fortran.hpp
  src/Enzo/hydro-mhd/CMakeLists.txt
  src/Enzo/hydro-mhd/EnzoMethodMHDVlct.cpp
  src/Enzo/hydro-mhd/EnzoMethodPpm.cpp
  src/Enzo/hydro-mhd/EnzoMethodPpml.cpp
  src/Enzo/hydro-mhd/SetMinimumSupport.cpp
  src/Enzo/hydro-mhd/SolveHydroEquations.cpp
  src/Enzo/hydro-mhd/SolveMHDEquations.cpp
  src/Enzo/hydro-mhd/hydro-mhd.hpp
  src/Enzo/hydro-mhd/ppm_fortran/CMakeLists.txt
  src/Enzo/hydro-mhd/ppm_fortran/ppm_fortran.hpp
  src/Enzo/hydro-mhd/ppml_fortran/CMakeLists.txt
  src/Enzo/hydro-mhd/ppml_fortran/ppml_fortran.hpp
  src/Enzo/hydro-mhd/riemann/CMakeLists.txt
  src/Enzo/hydro-mhd/riemann/EnzoRiemann.cpp
  src/Enzo/hydro-mhd/riemann/EnzoRiemann.hpp
  src/Enzo/hydro-mhd/toolkit/CMakeLists.txt
  src/Enzo/hydro-mhd/toolkit/EnzoBfieldMethod.cpp
  src/Enzo/hydro-mhd/toolkit/EnzoBfieldMethod.hpp
  src/Enzo/hydro-mhd/toolkit/EnzoBfieldMethodCT.cpp
  src/Enzo/hydro-mhd/toolkit/EnzoBfieldMethodCT.hpp
  src/Enzo/hydro-mhd/toolkit/EnzoIntegrationQuanUpdate.cpp
  src/Enzo/hydro-mhd/toolkit/EnzoIntegrationQuanUpdate.hpp
  src/Enzo/hydro-mhd/toolkit/EnzoLazyPassiveScalarFieldList.cpp
  src/Enzo/hydro-mhd/toolkit/EnzoLazyPassiveScalarFieldList.hpp
  src/Enzo/hydro-mhd/toolkit/EnzoReconstructor.cpp
  src/Enzo/hydro-mhd/toolkit/EnzoReconstructor.hpp
  src/Enzo/hydro-mhd/toolkit/EnzoReconstructorNN.cpp
  src/Enzo/hydro-mhd/toolkit/EnzoReconstructorNN.hpp
  src/Enzo/hydro-mhd/toolkit/EnzoReconstructorPLM.hpp
  src/Enzo/hydro-mhd/toolkit/EnzoSourceGravity.cpp
  src/Enzo/hydro-mhd/toolkit/EnzoSourceGravity.hpp
  src/Enzo/hydro-mhd/toolkit/EnzoSourceInternalEnergy.cpp
  src/Enzo/hydro-mhd/toolkit/EnzoSourceInternalEnergy.hpp
  src/Enzo/hydro-mhd/toolkit/toolkit.hpp
  src/Enzo/initial/EnzoInitialBCenter.cpp
  src/Enzo/utils/EnzoPermutedCoordinates.hpp
Labels: build-system

#340 Introduce `EnzoPhysicsGravity`
  doc/source/devel/index.rst
  doc/source/devel/physics.rst
  doc/source/param/method.incl
  doc/source/param/method_ppm.incl
  doc/source/param/physics.incl
  doc/source/user/problem_physics.rst
  input/Cosmology/method_cosmology.incl
  input/Gravity/jeans_wave/initial_jeans.incl
  input/Gravity/method_gravity_cg.incl
  input/LoadBalance/test_balance.incl
  input/test_cosmo.incl
  src/Enzo/cosmology/EnzoPhysicsCosmology.hpp
  src/Enzo/enzo-core/EnzoConfig.cpp
  src/Enzo/enzo-core/EnzoConfig.hpp
  src/Enzo/enzo-core/EnzoProblem.cpp
  src/Enzo/enzo-core/enzo.cpp
  src/Enzo/enzo.ci
  src/Enzo/enzo.hpp
  src/Enzo/enzo_constants.hpp
  src/Enzo/gravity/EnzoMethodBackgroundAcceleration.cpp
  src/Enzo/gravity/EnzoMethodGravity.cpp
  src/Enzo/gravity/EnzoMethodGravity.hpp
  src/Enzo/gravity/EnzoPhysicsGravity.hpp
  src/Enzo/gravity/gravity.hpp
  src/Enzo/hydro-mhd/SetMinimumSupport.cpp
  src/Enzo/hydro-mhd/SolveHydroEquations.cpp
  src/Enzo/initial/EnzoInitialInclinedWave.cpp
  src/Enzo/initial/EnzoInitialIsolatedGalaxy.cpp
  src/Enzo/initial/EnzoInitialShuCollapse.cpp
  src/Enzo/particle/formation/EnzoMethodBondiHoyleAccretion.cpp
  src/Enzo/particle/formation/EnzoMethodSinkMaker.cpp
  src/Enzo/particle/formation/EnzoMethodStarMaker.cpp
  src/Enzo/particle/formation/EnzoMethodStarMakerSTARSS.cpp
  src/Enzo/particle/formation/EnzoMethodStarMakerStochasticSF.cpp
Labels: gravity

#298 Suppress warnings charm++ module headers
  cmake/charm.cmake
  src/Enzo/CMakeLists.txt
Labels: build-system

#303 More starss fixes
  src/Enzo/particle/feedback/EnzoMethodFeedbackSTARSS.cpp
  src/Enzo/particle/formation/EnzoMethodStarMakerSTARSS.cpp
Labels: bug

#315 Support running VL+CT Integrator as a single stage integrator
  doc/source/param/method_mhd_vlct.incl
  doc/source/user/problem_method.rst
  input/Checkpoint/checkpoint_vlct.in
  input/FluxCorrect/inclined_contact_vl.incl
  input/vlct/vl.incl
  src/Enzo/enzo-core/EnzoConfig.cpp
  src/Enzo/enzo-core/EnzoConfig.hpp
  src/Enzo/enzo-core/EnzoProblem.cpp
  src/Enzo/hydro-mhd/CMakeLists.txt
  src/Enzo/hydro-mhd/EnzoMHDIntegratorStageCommands.cpp
  src/Enzo/hydro-mhd/EnzoMHDIntegratorStageCommands.hpp
  src/Enzo/hydro-mhd/EnzoMethodMHDVlct.cpp
  src/Enzo/hydro-mhd/EnzoMethodMHDVlct.hpp
Labels: enhancement, hydro/mhd
